# ========================================================================= #
# This docker files was built by the Perforce Software Swarm team to demo   #
# Swarm in a docker environment.                                            #
# ========================================================================= #
version: '2'

services:
  helix.base:
    build:
      context: containers/helix-base
    image: perforce/helix-base-ubuntu20:latest
    hostname: helix-base
    domainname: helix
    tty: false

  helix.swarm:
    build:
      #network: host
      context: containers/helix-swarm
      args:
        - SWARM_VER=${SWARM_VER:-latest}
    image: perforce/helix-swarm:${SWARM_VER:-latest}
    environment:
     - SWARM_USER=${SWARM_USER:-swarm}
     - SWARM_PASSWD=${SWARM_PASSWD:-HelixDockerBay94}
     - SWARM_MAILHOST=${SWARM_MAILHOST:-localhost}
     - SWARM_HOST=${SWARM_HOST:-helix.swarm}
     - SWARM_REDIS=${SWARM_REDIS:-redis}
     - SWARM_FORCE_EXT=${SWARM_FORCE_EXT:-n}
     - P4D_SUPER=${P4D_SUPER:-super}
     - P4D_SUPER_PASSWD=${P4D_SUPER_PASSWD:-HelixDockerBay94}
     - P4D_PORT=${P4D_PORT:-ssl:helix.p4d:1666}
    hostname: helix-swarm
    domainname: helix
    volumes:
      - ./storage/swarm-data:/opt/perforce/swarm/data
      - ./storage/file:/opt/perforce/etc/file
    ports:
      - ${PUBLIC_HTTP:-80}:80
    working_dir: /opt/perforce/swarm
    depends_on:
      - helix.redis
    tty: false


  helix.redis:
    image: "redis"
    hostname: helix.redis
    domainname: helix
    
    command: redis-server --protected-mode no --port 7379 --appendonly yes
    
    volumes:
      - ./storage/redis-data:/data
